#!/usr/bin/env bash
# Script that installs and configures Nginx with a 301 redirect

# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

# Allow Nginx through firewall
ufw allow 'Nginx HTTP'

# Create index page
echo "Hello World!" > /var/www/html/index.html

# Add redirection configuration
sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart
