#!/usr/bin/env bash
# Script that configures Nginx with custom 404 page

# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

# Allow Nginx through firewall
ufw allow 'Nginx HTTP'

# Create index page
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add redirection and custom 404 configuration
sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart
